### PR TITLE
[fix] change font to Plus Jakarta Sans

### PR DESCRIPTION
**Pull request by TheCatLady**
# Description

Updating font to be consistent with website, docs, etc.

# To-Dos

- [x] Extract i18n strings via `yarn i18n:extract`
- [x] Check formatting via `yarn format:check`
- [x] Lint via `yarn lint` and `yarn lint:tsc`
- [x] Test via `yarn test`

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://some.engineering/code-of-conduct).

### CODE REVIEW

**Review by sijav — APPROVED** [review]
LGTM

**Review by sijav — CHANGES_REQUESTED** [review]
It's not just the font, the whole style needs to change, a font change simply will break so many things in the UI, the size should match the previous font as well

**Review by sijav — APPROVED** [review]
LGTM @aquamatthias @lloesche what do you think?

**Review by aquamatthias — APPROVED** [review]
looks awesome to me

**Pull request merged**
